export const SET_BOOKS_DATA_IN_PROGRESS = 'SET_BOOKS_DATA_IN_PROGRESS';
export const SET_BOOKS_DATA_SUCCESS = 'SET_BOOKS_DATA_SUCCESS';
export const SET_BOOKS_DATA_FAILED = 'SET_BOOKS_DATA_FAILED';
export const CHANGE_BOOK = 'CHANGE_BOOK';
export const DELETE_BOOK = 'DELETE_BOOK';